#ifndef COMMON_BL_PARTITION_H
#define COMMON_BL_PARTITION_H

#include <stdint.h>

#define BL_FLASH_BASE_ADDR          0x08000000UL
#define BL_FLASH_TOTAL_SIZE         0x00080000UL
#define BL_FLASH_END_ADDR           (BL_FLASH_BASE_ADDR + BL_FLASH_TOTAL_SIZE - 1UL)
#define BL_FLASH_PAGE_SIZE          0x00001000UL

#define BL_BOOTLOADER_START_ADDR    0x08000000UL
#define BL_BOOTLOADER_SIZE          0x00010000UL
#define BL_BOOTLOADER_END_ADDR      0x0800FFFFUL

#define BL_PARAM_START_ADDR         0x08010000UL
#define BL_PARAM_SIZE               0x00001000UL
#define BL_PARAM_END_ADDR           0x08010FFFUL

#define BL_APP_START_ADDR           0x08011000UL
#define BL_APP_SIZE                 0x00020000UL
#define BL_APP_END_ADDR             0x08030FFFUL

#define BL_APP_BACKUP_START_ADDR    0x08031000UL
#define BL_APP_BACKUP_SIZE          0x00020000UL
#define BL_APP_BACKUP_END_ADDR      0x08050FFFUL

#define BL_FIRMWARE_STAGING_START_ADDR 0x08051000UL
#define BL_FIRMWARE_STAGING_SIZE       0x00020000UL
#define BL_FIRMWARE_STAGING_END_ADDR   0x08070FFFUL

#define BL_BOOT_START_ADDR          BL_BOOTLOADER_START_ADDR
#define BL_BOOT_SIZE                BL_BOOTLOADER_SIZE
#define BL_BOOT_END_ADDR            BL_BOOTLOADER_END_ADDR

#define BL_APP1_START_ADDR          BL_APP_START_ADDR
#define BL_APP1_SIZE                BL_APP_SIZE
#define BL_APP1_END_ADDR            BL_APP_END_ADDR

#define BL_STAGING_START_ADDR       BL_FIRMWARE_STAGING_START_ADDR
#define BL_STAGING_SIZE             BL_FIRMWARE_STAGING_SIZE
#define BL_STAGING_END_ADDR         BL_FIRMWARE_STAGING_END_ADDR

#endif /* COMMON_BL_PARTITION_H */
